# Generated by Django 4.0.4 on 2022-06-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
