# Generated by Django 4.0.4 on 2022-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='email',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
